### ISSUE TITLE
parameters->ice_candidates can't free complete

### ISSUE THREAD

**Issue by lxlenovostar** [rawrtc/rawrtc-terminal-demo#15]
we only free `parameters->ice_candidates ` in `parameters_destroy`.
But we reference it twice by:
```
ws_established_handler ==>
print_local_parameter    ==>
                                             client_encode_parameters  ==>
                                                                                            client_get_parameters==>
                                                                                                      rawrtc_ice_gatherer_get_local_candidates

```

**Comment by lgrahl** [comment]
Do you use copy & paste mode while specifying a valid WS URL? Otherwise that doesn't happen.

**Comment by lxlenovostar** [comment]
You are right, I update the rawrtc-terminal.

**Comment by lgrahl** [comment]
Maybe specifying a valid URL should disable usage of `print_local_parameter`.

**Comment by lxlenovostar** [comment]
I use  WS mode, but I still call `print_local_parameter `to get local information .
Thank you.
