### ISSUE TITLE
cmake fails: No package 'librawrtc' found

### ISSUE THREAD

**Issue by ClosetMonkey** [rawrtc/rawrtc-terminal-demo#17]
I installed rawrtc/rawrtc eailer succesfullly however now I'm trying to install rawrtc/rawrtc-terminal-demo and getting cmake errors. First error was that re and rew were not installed, so I had to cd into each of the deps folder in rawrtc/build/dependencies(re, rew) and run sudo make install for each. This fixed the errors "No package 're' found" and  "No package 'rew' found" but now it's failing at librawrtc.

**Comment by lgrahl** [comment]
Let me know of the precise dist you're using, so I can try to reproduce this. :slightly_smiling_face:

**Comment by lgrahl** [comment]
I've since replaced CMake in RAWRTC, so we'll do the same in this demo eventually. #21
